### ISSUE TITLE
Caching for HpkeConfig

### ISSUE THREAD

**Issue by ekr** [abetterinternet/prio-documents#106]
It seems silly to have clients revalidating the HPKE key for each request, so we probably want some kind of caching. I'm not sure HTTP Caching is quite what we want, but something... 

@martinthomson @mnot recommendations?

**Comment by martinthomson** [comment]
I'm going to need a little more context to provide good advice.

If we don't need key consistency (it doesn't appear so) and you only need correctness, then the client should just be able to talk directly to the collector and get keys periodically.  HTTP caching works fine for that purpose.

This would also need a rejection message so that the collector (or the leader on their behalf - the leader is more likely to learn about bad key identifiers before clients) can reject an out-of-date key in case the cache needs to be invalidated.

**Comment by ekr** [comment]
We do not need key consistency.

The rejection message seems like a good idea.
