### ISSUE TITLE
Some notes on requirements

### ISSUE THREAD

**Issue by ekr** [abetterinternet/prio-documents#27]
I tend to think of this from two perspectives (1) the client and
(2) the collector. At a high level, we expect them to coordinate.

The basic unit here is the measurement, which is just a value
collected by the client. In a normal system, each value is
characterized by:

- A name
- A type [scalar, integer, etc.]
- Externally, some description of what it measures
- Some description of what reasnable values are (so we can do outlier
  rejection)

In Prio, you would also have:

- The aggregation function you want to use with the measurement.
- The precise ranges of a valid input (replacing the "reasonable")
  filter above

Note that this might mean you needed to duplicate measurements if you
wanted to be able to do multiple aggregation functions.  This isn't
necessarily with traditional telemetry.

This information needs to be propagated both to the client and the
collector and they need to match. Practically, once a name is
reserved, its properties shouldn't change because otherwise things get
weird. Though sometimes we will slightly change how we collect some
measurement a bit, but keep the types the same, etc.

Operationally, clients will have some set of measurements that they
maintain and then will just periodically send them all to the server
in a single package (Mozilla calls this a "ping"). In Mozilla
telemetry this is just a JSON blob, e.g.,

         "scalars": {
            "contentblocking.trackers_blocked_count": 258,
            "media.element_in_page_count": 42,
            "browser.engagement.session_time_including_suspend": 90858058,
            "browser.engagement.active_ticks": 612,
            "browser.engagement.session_time_excluding_suspend": 49487949
          },

When you want to add a new measurement, you just add a new entry to
the JSON blob. And in principle you could remove them, though that's
less common. So, for instance, version 20 might have these scalars and
version 21 might have these plus another.

On the collector side, what you generally want to be able to do is to
filter the reports by demographic type information (e.g., browser
version, location, time) and then compute some aggregate over the
filtered result. For instance, suppose you wanted to know the fraction
of IPv4 versus IPv6, you might just take every client that reported
that measurement, but you might also want to look at Beta versus
Release. One important implication is that when you are looking
at measurement A, you don't care if the client reported measurement
B. And in particular, if some clients report [A, B] and others report
[A], you want to capture all of them (unless you don't!).

Obviously Prio limits what you can do here. In particular:

- You can't just compute any statistic over a given measurement,
  but only the ones compatible with the encoding.

- It's not safe to let people just compute aggregates over
  arbitrary-sized subsets of the data because then they can
  pull out specific reports.

However, we'd obviously like to support as flexible queries as
possible. In particular, it's desirable to have modes in which
you can "drill down" into the data. For instance, you might
notice that the rate of some error had gone up recently and
want to try to isolate it to some subpopulation. This implies
that you don't just want pure batch processing.

**Comment by cjpatton** [comment]
Thanks for writing up this clear description of the use case, @ekr. Your understanding of the limits of Prio with respect to this particular usage appears to match my own. The good news is that there's lots of ways to provide flexibility of the system, though perhaps at the cost of time complexity, communication overhead, or both. By way of fleshing out the design space, let me sketch what I see as the two possible extremes.

**Maximizing flexibility.** Let's start with how we would maximize flexibility of the system. Essentially what we need to do is move all metadata and versioning logic outside of Prio. Concretely, we secret share and validate each value in the JSON object Individually. So instead of the plaintext JSON blob above, each aggregator would see something like
```
     "scalars": {
        "contentblocking.trackers_blocked_count": {
           "proof share": <share of proof 1>, 
           "input share": <share of input 1>
        },
        "media.element_in_page_count": {
           "proof share": <share of proof 2>, 
           "input share": <share of input 2>
        },
        "browser.engagement.session_time_including_suspend": {
           "proof share": <share of proof 3>, 
           "input share": <share of input 3>
        },
        "browser.engagement.active_ticks": {
           "proof share": <share of proof 4>, 
           "input share": <share of input 4>
        },
        "browser.engagement.session_time_excluding_suspend": {
           "proof share": <share of proof 5>, 
           "input share": <share of input 5>
        }
      }
```
Here, the proof and input shares look like sequences of random field elements. The aggregators would collectively validate each input using the proof share corresponding to their input share. Since there are 5 inputs here, the aggregators would do 5 runs of the input validation protocol. Notice, however, that since the runs are independent, it's possible to batch the messages together so that the round complexity (i.e, round trips over the network) is the same as if there were just one input to validate.

Having validated all of the inputs, the aggregators can do whatever they want with them. For example, if they want to compute a statistic over the measurements by all clients of a particular agent type, then each aggregator would simply sum up the inputs shares sent by clients with that agent type. (One only needs to take care that this doesn't reduce the anonymity set further than the threshold specified by the collector: see https://github.com/abetterinternet/prio-documents/issues/15.) Versioning is also pretty straightforward, since each input is labeled separately.

As you correctly point out, the main limitation of Prio is that you need to know in advance what sorts of statistics you want to compute over measurements. This is because the client needs to know beforehand how to encode and generate a proof for each input. However, inputs can be encoded in a way that allows for multiple statistics to be computed about the same set of measurements. For example, if we're already computing the mean over a set of measurements, then it's fairly cheap to add the standard deviation. We could also throw in other statistics, like median, min, or max, but we need to be careful because some statistics have a higher communication cost than others.

**Minimize overhead.** The main downside to the above approach is that it usually won't provide optimal time complexity or communication overhead. The reason, basically, is that by handling all of the inputs "monolithically", we can take advantage of redundancy in the structure of the input in order to construct a more efficient proof system. In particular, the JSON becomes simply
```
     "scalars": {
           "proof share": <share of proof>, 
           "input share": <share of input>
      }
```
and there are procedures for encoding and decoding this "monolithic input" as measurements `contentblocking.trackers_blocked_count`, `media.element_in_page_count`, and so on.

Here, the length of the input share is about the same as the sum of the lengths of the input shares above; however, it is often possible to reduce the size of the proof share significantly compared to the proof shares above. In more detail, the main way we optimize the proof size is by being creative in how we apply Theorem 4.3 of [[BBG+19]](https://eprint.iacr.org/2019/188.pdf). The proof size is linear in the number of "G-gate" evaluations in the validity circuit that recognizes valid inputs. If there is lots of redundancy in the validity circuit, then we can make G "big", thereby reducing the number evaluations of G and shortening the proof.

So what's the downside of the "monolithic input" approach? In terms of flexibility, it's still possible to do things like aggregate measurements based on agent type. Beta/Release, etc. However, versioning becomes much more difficult: if we want to change the set of measurements that are encoded by the input, then we would need to change the way we construct the proof system. This isn't so bad if the client and aggregators are running the same code (there are lots of situations in which this is feasible), but if they are running different code, then coordinating this will be significant.

**So, what do we do?** The best solution for a given deployment is going to lie somewhere in the middle of these two extremes. I think it should be a goal of ours to design the protocol in a way that allows deployments to make different trade-offs between flexibility and efficiency. Regardless of what trade-off a particular deployment makes, what is needed is a way of annotating inputs in a way that ensures clients and aggregators know how to generate and verify them. We also need a way of failing gracefully if an aggregator doesn't know how to verify an input.

That said, it's important to note that this problem isn't knew. It's somewhat akin to assigning code points to DH groups in TLS, in the sense that the code point prescribes the code that is going to be run by the parties.

**Comment by cjpatton** [comment]
@ekr, I wanted to follow up on the performance benefits of stuffing many measurements into the same proof. If we know in advance that clients will submit many measurements of the same type, then it's possible to construct a proof that is much smaller than the sum of the sizes of proofs for the individual measurements. The following PR for libprio-rs demonstrates this for vectors of booleans:
https://github.com/abetterinternet/libprio-rs/pull/30

The table compares the proof size of "Prio v2", the current proof system for boolean vectors, to "PolyCheckedVector", the proof system that the PR implements. Prio v2 constructs an `O(n)` sized proof, where `n` is the number of booleans. In terms of communication overhead, this is no better than constructing a constant-sized proof for each bit individually. PolyCheckedVector constructs a proof of size `O(sqrt(n))`.

The same optimization is possible for a vector of integers, so long as each of the integers has the same range of valid values. In fact, this optimization can be applied regardless of the set of aggregates we want for each integer, so long as as the set is the same for each aggregator.

This optimization won't make sense everywhere, of course, but one instance in which I can imagine using it is when clients report several counts or timings that have the same expected range.
