### ISSUE TITLE
Possible performance impact of decoupled verify / collect stages with heavy hitters

### ISSUE THREAD

**Issue by csharrison** [abetterinternet/prio-documents#44]
(moving a comment made in https://github.com/abetterinternet/prio-documents/pull/43 to an issue)
I have a high level concern with the architecture here, following up from our meeting on Wednesday related to heavy hitters.

**TL;DR evaluating a hierarchy at only a subset of levels (which are specified at query time) is not optimal for performance if the verification step does not have access to those specified levels.**

For heavy hitters, we are considering a model where records form a binary tree, where aggregates can be reported at different levels of the tree. There are a few possible ways this could go:

 1. For every record, verify and evaluate the entire binary tree (i.e. bit-by-bit evaluation)
 2. For every record, verify and evaluate only a subset of the tree (at the limit, this can look more like Prio which only evaluates the last level of the tree)
    2a. The subset of the tree to evaluate is configured within a particular record at record-creation time
    2b. The subset of the tree to evaluate is configured dynamically at collection / aggregation time

For our use-case (discussed in #18 (comment)), we are interested in (2b), for a few reasons:

(1) is potentially inefficient from both a performance and accuracy POV in that it requires more rounds, and additionally when used with differential privacy requires splitting a DP budget across all levels. Some prefixes might just not be interesting to the caller so we shouldn't waste privacy budget / compute on them.

(2a) is problematic in two dimensions.
-  Embedding configuration in records may compromise user privacy if the configurations can be set by an adversary colluding with one of the aggregators (e.g. you can leak log2(n choose k) bits of information if you allow any subset of k prefixes for an n-bit domain).
- Levels must be pre-specified at record-creation time, which is non-ideal if new information comes up at collection time which informs how aggregation should work (e.g. realizing you have fewer records than expected so it is better to focus on querying only up to a given prefix).

However, I think (2b) runs into a few issues with this architecture that separates verification from collection, in that without knowing the specific levels to evaluate, we run the risk of spending unnecessary compute verifying levels that will never end up being used. The protocol is more efficient (less computation, fewer rounds) if we can verify multiple levels at once (i.e. the levels the collector cares about).

Possible solutions:

1. Add a step where the collector and leader communicate prior to verification (but keep verification and collection separate)
2. More tightly couple "verify" and "collect" stages, so that verification can be done based on communication with the collector.
3. 
In our setting, the "leader" and "collector" roles are somewhat merged which aligns with option (1), but it seems like a good idea to make the general architecture robust to this use-case.

cc @schoppmp who is working on our C++ implementation of IDPFs.

**Comment by cjpatton** [comment]
Thanks for the feedback @csharrison! I've finally had a chance today to dig into the heavy hitters paper. I agree that the framework described in #43 isn't going to be feasible for heavy hitters. I think your option (2b) is the only way to go, as I explain below.

For context, #43 thinks of PA ("Private Aggregation") protocols as having three distinct "phases": 
* **Upload**: Each client uploads its input shares to the aggregators.
* **Verify**: The aggregators verify each client's input.
* **Collect**: Each aggregators add up their verified input shares and emits its output share to the collector.

In order to fit heavy hitters into his framework, we could take your option (1) or (2a). However, these options are only  feasible for very small inputs, say, `N=16`, where `N` is the length of each client input in bits. In order to make the protocol feasible for large inputs, heavy hitters involves multiple rounds of the Verify/Collect phases, where the output of the previous Collect phase is used to decide what to do in the next Verify phase. So that we're all on the same page about why interaction is necessary, I've included a brief overview of the protocol below [1]. (Please correct me if I've misunderstood anything!)

Accounting for this interaction in the protocol spec should be fairly straightforward. The delta, I think, is that there needs to be a way to re-run the Verify/Collect phases on the same inputs, but using different parameters each time, i.e., with different sets of prefixes specified by the collector.

___
[1] Here's a bird's eye view of the protocol, as I understand it. (I'm ignoring DP for now.) First, (**Upload**) each client generates IDPF shares of its `N`-bit input and sends a share to each aggregator. After all clients have uploaded their IDPF key shares, the collector and aggregators verify and collect the heavy hitters as follows. Let `S(1) = {0,1}`. For each `L=1, ..., N`:
1. (**Verify**) For each client upload:
  a. For each prefix `p` in `S(L)`, each aggregator evaluates its IDPF share on input of `p`.
  b. The aggregators verify (in zero-knowledge) that their IDPF outputs are well-formed, i.e., that only one of the outputs is `1` and the rest are `0`.
2. (**Collect**) 
  a. For each verified IDPF output, each aggregator adds up its shares and sends the resulting "histogram share" to the collector.
  b. The collector adds the histogram shares together to get the histogram. This encodes the frequency of each prefix `p` in `S(L)` among the client inputs.
  c. The collector assembles `S(L+1)`, the next set of candidate prefixes. To do so, it collects the set `M` of prefixes that appear at least `t` times in the histogram. It lets `S(L+1)` be the set of strings obtained by appending `1` or `0` to each element of `M`.
  d. Finally, the collector  disseminates `S(L+1)` among the aggregators.

What makes this feasible is that the size of each `S(L)` is at most the number of clients divided `t`.

**Comment by csharrison** [comment]
@cjpatton this sounds about right to me. Just a small nit but I wanted to point out that your (Collect) stage, multiple interactions with the collector are not strictly necessary. What you described is a zero-knowledge protocol but alternatively the aggregators could interact to learn the aggregates at each level and proceed down without interaction with the collector.

We discussed this variant a few weeks ago, it trades off aggregator knowledge with protocol simplicity (e.g. collectors don't need to follow an interactive protocol).

**Comment by cjpatton** [comment]
> @cjpatton this sounds about right to me. Just a small nit but I wanted to point out that your (Collect) stage, multiple interactions with the collector are not strictly necessary. What you described is a zero-knowledge protocol but alternatively the aggregators could interact to learn the aggregates at each level and proceed down without interaction with the collector.

Let me see if I understand you correctly. Concretely, the helper would send the leader its share of the aggregate at the end of each round. Next, the leader would use the aggregate shares to compute the next set of prefixes, then  send this to the helper for the next round.

If my understanding is right, then it seems to me that this is the same protocol as [1], but with leader == collector. What do you think?

> We discussed this variant a few weeks ago, it trades off aggregator knowledge with protocol simplicity (e.g. collectors don't need to follow an interactive protocol).

Maybe I'm missing something. I'll do my best to read the design doc you shared by the end of the week.

**Comment by csharrison** [comment]
> If my understanding is right, then it seems to me that this is the same protocol as [1], but with leader == collector. What do you think?

Yes that's right. I was outlining a "simpler" communication model where helpers communicated directly with each other but  in this architecture it would go through the leader.
