### ISSUE TITLE
Consider making Upload Start an idempotent GET

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-documents#48]
Per #43, the first step in the upload protocol is a POST to the leader server which returns information about helpers. In some yet to be specified cases, the response could include a challenge to be incorporated into reports. However I suspect that in most cases, the response will be static and so an idempotent, cacheable GET would be a better fit, especially since it would save clients a roundtrip to the helper on the hot path of submitting reports, and would make it possible for helpers to implement upload_start by putting some static content in a CDN.

HTTP GET requests don't have bodies, so we would have to figure out how to encode all the data in the current `PAUploadStartReq` into the `upload_start` URI, which could be done as either path fragments in the URI (i.e., `[leader]/upload_start/[task.version]/[task.id]`) or as query parameters (i.e., `[leader]/upload_start?version=[task.version];id=[task.id]`).

We would of course need to make sure that [the semantics of HTTP GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) don't preclude proof systems like the one alleged to exist in section 5.2 of "BBCp19".

**Comment by tgeoghegan** [comment]
Also, because the current protocol uses a POST for upload_start, the implication is that for every report they submit, clients need to hit `upload_start` and then `upload_finish`. If we make `upload_start` idempotent and cacheable, then that request can be skipped in the majority of cases. I suppose the significance of this depends on how we expect clients to use PDA: are they going to be continuously streaming hundreds or thousands of reports into the leader as events of interest occur (in which case I think eliminating `upload_start` requests is interesting) or are they expected to accumulate several reports locally before submitting them all in one or a few requests?

**Comment by cjpatton** [comment]
I agree this would be a good change, if we can swing it. It's notable that Prio v2 and HH don't require a random challenge from the leader. But as discussed, this is useful for other proof systems one might want to implement for Prio. For example, see the data type implemented here: https://github.com/abetterinternet/libprio-rs/pull/48. See below for an explanation.

There might be other ways to implement the challenge.
* One possibility is to derive the challenge from the TLS key schedule (or from whatever state the client and leader share for the secure channel). @ekr and @tgeoghegan  have both pointed out that adding this dependency on the underlying transport is problematic.
* Another possibility might be to use some external source of randomness that the leader trusts. [DRAND](https://drand.love/) comes to mind, though it is somewhat problematic because clients would effectively use the same randomness for some period of time. The security model of BBCp19 would need to be extended to account for this. (I believe this could be done.)
* Some other solution I'm missing?

____
This data type is used to compute the mean and variance of each integer in a sequence of integers. To do so, the client encodes each integer `x` of its input vector as a pair `(x_vec, xx)`, where `x_vec` is the representation of `x` as a bit vector and `xx` is equal to `x^2`. To prove validity of its input, the proof needs to do two things: verify that (a) `x_vec` is indeed a bit vector, and (b) the integer encoded by `x_vec` is the square root of `xx`.

In order to check these things efficiently, the proof system uses a random challenge generated by the leader. At a very high level, the client wants to prove that the following boolean conjunction holds: `x_vec[0]` is 1 or 0 *AND* `x_vec[1]` is 1 or 0 *AND* ... *AND* `x_vec` encodes the square root of `xx`. In Prio, we need to represent this conjunction as an arithmetic circuit, which the random challenge helps us do.

In a bit more detail now: Let's rewrite this expression as w[0] *AND* w[1] *AND* ... *AND* w[s]. As an arithmetic circuit, this expression is actually `v[0] + v[1] + ... + v[s]`, where `v[i] == 0` if and only if w[i] is true. If the input is valid, then the expression should evaluate to `0`. But because we're talking about field elements, a malicious client may try to play games like setting `v[i] = 2` and `v[j] = -2` so that the sum is still `0`, but the statement is false. To detect this, we actually compute the following expression: `v[0] * r + v[1] * r^2 + ... v[s] * r^(s+1)`, where `r` is a randomly chosen field element. If the statement is true, then the expression evaluates to `0`. If the statement is false, then with high probability, the expression will evaluate to something other than `0`. (This idea comes from Theorem 5.3)

**Comment by tgeoghegan** [comment]
Thank you for the detailed explanalation @cjpatton! Having thought about it more, I suspect an HTTP GET wouldn't be the right way to support proof systems that need a challenge. Assuming that a unique challenge is needed for every report[^1], then intuitively the leader would have to maintain a mapping of reports to issued challenges so that the leader and helper(s) can later use the challenge value when evaluating the client's proof.

But now that the leader has to maintain state per-report, I think the upload protocol is missing a notion of a report identifier. The `PAUploadStartReq` contains a `PATask`, but IIUC the `PATask` will be the same across many reports[^2] (e.g., if a browser is sending daily reports on how often users click a button, they use the same `PATask` every time they submit). So `PAUploadStartResp` needs to include a report ID, which must be echoed back to the leader in `PAUploadFinishReq` so that the leader can look up the challenge for the report. 

[^1] Is this true? Or would it suffice for each `PATask` to use the same challenge across multiple reports?
[^2] I notice that the design doc lacks a strong definition of a report and how it relates to tasks, inputs, measurements: #53
 because GET should be "safe" in the sense of not changing any server state, and it seems like the server would have to maintain a mapping of reports to issued challenges so that the leader and helper can later use the challenge value when evaluating the client's proof.

**Comment by tgeoghegan** [comment]
Continuing on the assumption that `upload_start` causes a state change on the leader, POST is then the appropriate HTTP method to use. [Mozilla sez POST is cacheable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST), though it's a little unusual. There may be some big drawback to cacheable POST responses, but I think that might let us support proof systems that require live challenges while also eliminating the majority of `upload_start` requests when the proof system is such that the `PAUploadStartResp` will change very rarely.

**Comment by tgeoghegan** [comment]
> The requirement for the leader to keep state across upload start and upload finish may be avoidable. Suppose the leader has a long-lived PRF key K. It would could choose a random nonce N, compute R = PRF(K, N) as the challenge, and hand (N, R) to the client in its upload start response. The client would then use R to generate the proof and send N to the leader in its upload finish request. The leader could then re-derive R.

I like this a lot! I'm a big fan of deterministic derivation schemes like this -- besides reintroducing the possibility of an idempotent GET, eliminating storage requirements for challenges makes it much easier to scale up leaders. If the report IDs are big enough (UUIDs?) we could even use them as `N`.

> @chris-wood and I kicked around the idea of having the client generate a report ID. I think this may end up being useful, but we weren't sure if it was better to have the leader choose it or the client.

I would say the leader, because if you let the client do it, then the leader would have to check for things like collisions with existing report IDs or other malicious ID choices. If the leader chooses it, then all it has to do is generate a few bytes of randomness.

> > [^1] Is this true? Or would it suffice for each `PATask` to use the same challenge across multiple reports?
> 
> To conform to the security model of BBCp19, each report would need its own challenge. It may be possible to relax this, but this would be risky.

I agree.

**Comment by cjpatton** [comment]
@henrycg, we'd appreciate your feedback on this issue because it involves security considerations for ZKP systems on secret-shared data [1]. I'll quickly sum up the problem so that you don't need to worry about the conversation above.

The problem at hand regards systems like [1, Theorem 5.3] that require interaction between the prover and verifier. Specifically, we're considering a special case of Theorem 5.3 in which the verifier sends the prover a random "challenge" `R` that is used to generate and verify a (non-interactive) FLPCP (call it `P`):
```
                    Prover                               Verifier
                        | (upload start)                  |
                        |-------------------------------> |  Generate R
                        |                      R          |
                        | <------------------------------ |
                        | (upload finish)      P          |
             Generate P |-------------------------------> |  Verify P
             (using R)  |                                 |  (using R)
                        V                                 V
```
We refer to the prover's first and second messages as "upload start" and "upload finish" respectively. Each message corresponds to an HTTP request made by a web client to a web server. Ideally, the verifier would be able to handle these requests *statelessly*, i.e., without having to store `R`.

Consider the following change. Suppose the verifier has a long-term PRF key `K`. In response to an upload start request, it chooses a unique "upload id" `N` --- maybe this is a 16-byte integer chosen at random --- and computes `R = PRF(K, N)` and sends `(R, N)` to the prover. In the upload finish request, the prover sends `N` so that the verifier can re-derive `R` instead of needing to remember it:
```
                    Prover                               Verifier^K
                        | (upload start)                  |
                        |-------------------------------> |  Generate N
                        |                     (R, N)      |  Compute R = PRF(K, N)
                        | <------------------------------ |
                        | (upload finish)     (P, N)      |
             Generate P |-------------------------------> |  Verify P
             (using R)  |                                 |  (using R = PRF(K, N))
                        V                                 V
```
The (potential) problem with this variant is that a malicious client is able to replay a challenge as many times as it wants.
This behavior isn't accounted for in Definition 3.9, so when you try to "compile" this system into a ZKP on secret-shared data as described in Section 6.2 and consider its security with respect to Definition 6.4 (Setting I), you can no longer appeal to Theorem 6.6 to reason about its security.

Our question is therefore: **What impact do you expect this change to have on the soundness of the system?** Can you think of an attack that exploits the fact that challenges can be replayed? My expectation is that the problem is merely theoretical, i.e., we ought to be able to close the gap with an appropriate refinement of Definition of 3.9 and reproving Theorem 5.3.

[1] https://eprint.iacr.org/2019/188

**Comment by henrycg** [comment]
Thanks for looping me in. In the discussion below, I am assuming that the client sends its data vector (called "x" in the paper [1]) at the same time as it sends its proof to the verifier. Even if the client sends its data vector in the first message, it seems that the client can reuse an (R,N) pair from upload request 1  to later submit upload request 2, in which case the client sees (R, N) before it chooses its data vector and proof. So I think we can assume that the client's data vector and proof can depend on the verifier's random value R. (I'll call this value "r" to match the paper.)

For soundness: the client/prover must commit to its data vector _before_ it learns the verifier's random value r. If the prover can choose its data value and proof in a way that depends on the verifier's randomness r, the soundness guarantee no longer holds. There is also an efficient attack. So I suspect that the stateless-verifier optimization is unsound.

The attack works as follows: given r, the verifier finds a non-satisfying vector x such that \sum_i r_i C(A_i(x)) = 0, again using the notation from Theorem 5.3 in the paper [1]. For the circuits C used in most applications, it will be easy to find such a vector x. Then, the prover constructs a proof that x that  \sum_i r_i C(A_i(x)) = 0. The proof is valid, so the verifier will accept always.


To remove interaction, the Fiat-Shamir-like technique in Section 6.2.3 is probably the best way to go. We only sketched the idea in the paper (without formal analysis or proof) but if it's going to be important for your application, I'm happy to sanity-check the protocol you come up with.

Another idea—the details of which I have not checked carefully—would be to modify your protocol as follows:

1. The prover sends its data vector x to verifiers, split into k shares x_1, ..., x_k—one for each of the k verifiers.
2. Each verifier holds a PRF key k_i computes r_i = PRF(k_i, x_i) and they return r = r_1 + ... + r_k to the prover. The verifiers store no state.
3. The prover computes the proof \pi and sends (x_1, \pi_1), ..., (x_k, \pi_k) to the verifiers—again, one for each of the k verifiers. Each verifier computes r_i = PRF(k_i, x_i), they jointly compute r = r_1 + ... + r_k, and check the proof using randomness r.

The Fiat-Shamir-like approach seems slightly cleaner to me, since it only requires a single prover-to-verifier message.

Either way, please let me know if I misunderstood your question or if anything else here is unclear.

[1] https://eprint.iacr.org/2019/188

**Comment by cjpatton** [comment]
Thanks for the nice explanation, Henry. It's perfectly clear and answers my question. It also points to something that I, for one, missed the importance of: the need for the prover to "commit" to the input shares before generating the r-dependent proof. I appreciate you pointing this out.

The only requirement for making upload start not idempotent is so that the randomness r can be sent to the client. It would be nice to do away with this requirement. I think the way forward is using the Fiat-Shamir technique. @henrycg, I'll get cracking on this and let you know when I have something for you to look at.

**Comment by cjpatton** [comment]
@henrycg, I believe the change is something like this. Let `H` be a hash function with range `\bits^h`. Suppose there are `k` verifiers. The prover proceeds as follows:
- Splits its inputs `x` into shares `x_1, ..., x_k`.
- For each `i \in \{1, ..., k\}`, do:
  - Choose blinding factor `V_i` from `\bits^h` at random.
  - Let `R_i \gets H(i, x_i, V_i)`.
- Set `R \gets R_1 \xor ... \xor R_k`.
- Derive field element `r` from `R` (e.g., seed a PRNG with `R` and map the output to a field element by rejection sampling on chunks of the output).
- Generate the proof `\pi` using `x` and `r`.
- Split `\pi` into shares `\pi_1, ..., \pi_k`.
- For each `i \in \[1, ..., k\}` send `(x_i, \pi_i, V_i)` to the `i`-th verifier.

**Comment by henrycg** [comment]
Yes, this looks right to me!

**Comment by cjpatton** [comment]
As of https://github.com/abetterinternet/prio-documents/pull/79, the upload start request no longer exists. When we're ready to specify Prio, we'll want to include the Fiat-Shamir approach for protocols that use joint randomness. I've noted this and am closing the issue.
