### ISSUE TITLE
Why does PATask include version?

### ISSUE THREAD

**Issue by ekr** [abetterinternet/prio-documents#67]
This seems unnecessary.

**Comment by cjpatton** [comment]
The PATask is always the first bit of a protocol message, and the version is the first bit of the PATask. I figured it would be helpful to version each message because messages are carried by HTTP requests. There might be a simpler/better way to do this.

**Comment by ekr** [comment]
I don't think we should assume that's the case. If we want to have the version not determined at the URL level (a mistake, IMO) then we should have some sort of message wrapper that contains that, rather than overloading PATask.

**Comment by tgeoghegan** [comment]
I'm inclined to agree with @ekr: we're discussing versioning the whole API in #61, so PATask doesn't need to also provide version information. So, setting aside the question of message format versions, is there any value in maintaining a version on PATasks at the protocol level? I say no, because we want to be able to treat different PATasks completely independently and don't otherwise have any notion of a relationship between any two PATasks in the protocol.
